### ISSUE TITLE
Monsters don't immediately transition to the death animation when dying

### ISSUE THREAD

**Issue by Eclmist** [Eclmist/Aether#104]
**Describe the bug**
Monsters don't immediately transition to the death animation when dying
**Severity:** 
**Probability:** 

**To Reproduce**
1. Kill a monster

**Expected behavior**
The monster should transition from whatever animation to the death animation immediately. The death particle vfx should only play after the death animation is complete.

**Screenshots (Optional)**

**Any Other Information (Optional)**

**Comment by heze8** [comment]
I didn't see any issues with the plant and mushroom ones but I tweaked the values, and I believe I fixed the golem one
