### ISSUE TITLE
Button on top left of main menu opens forge networking console

### ISSUE THREAD

**Issue by DarkDestry** [Eclmist/Aether#88]
**Describe the bug**
Button on top left of main menu opens opens forge networking console

**Severity:**  Low
**Probability:** Med

**To Reproduce**
1. Open game.
2. Press button on top left of screen

**Expected behavior**
That shouldnt exist 

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/3728955/79199232-44d89f80-7e67-11ea-957c-0833e32a8590.png)

**Comment by Eclmist** [comment]
@tcgj Could you figure out how to hide the button
