### ISSUE TITLE
When not host, Start game does nothing

### ISSUE THREAD

**Issue by DarkDestry** [Eclmist/Aether#93]
**Describe the bug**
When not host, Start game does nothing

**Severity:** Med
**Probability:** High

**To Reproduce**
1. Join game
2. Note the existence of start game button

**Expected behavior**
Show "You are not host" or "Wait for the host to start" or Remove button

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/3728955/79200863-af8ada80-7e69-11ea-9fe3-bdfa4e46f89b.png)

**Comment by Eclmist** [comment]
@tcgj could you hide the start game UI button when not host?
